### ISSUE TITLE
Right side panel menu is cut off on the right

### ISSUE THREAD

**Issue by lordjeb** [erizocosmico/foundry-thewalkingdead#2]
The side panel on the right (chat, actors, compendiums, etc.) is cut off at the top. I can see half of the settings icon, and cannot see the scroll arrows (if any) at all. Not a big deal, but if you feel like fixing it...

You can see an example on this live solo play YouTube video: https://www.youtube.com/watch?v=Oq7jFbwCyCM

Foundry v11 build 307
TWD system 1.0.4
No modules active

**Comment by erizocosmico** [comment]
Ooh, yes, it's because of the cards tab. I usually have it removed, so I didn't notice

**Comment by erizocosmico** [comment]
Should be fixed in v1.0.5. Thanks for reporting!
